import type { NodeDefinition } from '../../../shared/types';

export const nodeDefinitions: NodeDefinition[] = [
  // ============ 触发器 ============
  {
    type: 'startup',
    category: 'trigger',
    label: '启动触发',
    description: 'FlowDesk 启动时自动触发',
    icon: 'Power',
    color: '#818cf8',
    inputs: [],
    outputs: [{ id: 'out', label: '输出', dataType: 'any' }],
    outputFields: [
      { key: 'triggeredAt', label: '触发时间', type: 'string' },
    ],
    defaultData: {},
    configSchema: [],
  },
  {
    type: 'manual',
    category: 'trigger',
    label: '手动触发',
    description: '手动点击运行工作流',
    icon: 'Play',
    color: '#818cf8',
    inputs: [],
    outputs: [{ id: 'out', label: '输出', dataType: 'any' }],
    outputFields: [
      { key: 'triggeredAt', label: '触发时间', type: 'string' },
    ],
    defaultData: {},
    configSchema: [],
  },
  {
    type: 'cron',
    category: 'trigger',
    label: '定时触发',
    description: '按 cron 表达式定时触发',
    icon: 'Clock',
    color: '#818cf8',
    inputs: [],
    outputs: [{ id: 'out', label: '输出', dataType: 'any' }],
    outputFields: [
      { key: 'triggeredAt', label: '触发时间', type: 'string' },
      { key: 'cronExpression', label: 'Cron 表达式', type: 'string' },
    ],
    defaultData: { cronExpression: '0 9 * * *', timezone: 'Asia/Shanghai' },
    configSchema: [
      { key: 'cronExpression', label: 'Cron 表达式', type: 'cron', required: true, placeholder: '0 9 * * *' },
      { key: 'timezone', label: '时区', type: 'text', placeholder: 'Asia/Shanghai' },
    ],
  },
  {
    type: 'file-watch',
    category: 'trigger',
    label: '文件监听',
    description: '监听文件变化触发',
    icon: 'Eye',
    color: '#818cf8',
    inputs: [],
    outputs: [{ id: 'out', label: '输出', dataType: 'any' }],
    outputFields: [
      { key: 'filePath', label: '文件路径', type: 'string' },
      { key: 'fileName', label: '文件名', type: 'string' },
      { key: 'eventType', label: '事件类型', type: 'string' },
      { key: 'fileSize', label: '文件大小', type: 'number' },
    ],
    defaultData: { watchPath: '', patterns: '', events: 'add' },
    configSchema: [
      { key: 'watchPath', label: '监听路径', type: 'file-picker', required: true },
      { key: 'patterns', label: '匹配模式', type: 'text', placeholder: '*.pdf,*.jpg（逗号分隔）' },
      { key: 'events', label: '事件类型', type: 'select', options: [
        { label: '新增', value: 'add' },
        { label: '修改', value: 'change' },
        { label: '删除', value: 'delete' },
      ]},
    ],
  },
  {
    type: 'hotkey',
    category: 'trigger',
    label: '快捷键触发',
    description: '全局快捷键触发',
    icon: 'Keyboard',
    color: '#818cf8',
    inputs: [],
    outputs: [{ id: 'out', label: '输出', dataType: 'any' }],
    outputFields: [
      { key: 'triggeredAt', label: '触发时间', type: 'string' },
    ],
    defaultData: { accelerator: '' },
    configSchema: [
      { key: 'accelerator', label: '快捷键', type: 'hotkey', required: true },
    ],
  },

  // ============ 动作 ============
  {
    type: 'file-operate',
    category: 'action',
    label: '文件操作',
    description: '移动、复制、删除、重命名文件',
    icon: 'FolderSync',
    color: '#4f6ef7',
    inputs: [{ id: 'in', label: '输入', dataType: 'any' }],
    outputs: [{ id: 'out', label: '输出', dataType: 'object' }],
    outputFields: [
      { key: 'moved', label: '已移动路径', type: 'string' },
      { key: 'copied', label: '已复制路径', type: 'string' },
      { key: 'deleted', label: '已删除路径', type: 'string' },
      { key: 'renamed', label: '已重命名路径', type: 'string' },
      { key: 'to', label: '目标路径', type: 'string' },
    ],
    defaultData: { operation: 'move', sourcePath: '', targetPath: '' },
    configSchema: [
      { key: 'operation', label: '操作', type: 'select', required: true, options: [
        { label: '移动', value: 'move' },
        { label: '复制', value: 'copy' },
        { label: '删除', value: 'delete' },
        { label: '重命名', value: 'rename' },
      ]},
      { key: 'sourcePath', label: '源路径', type: 'text', placeholder: '支持 {{变量}} 插值' },
      { key: 'targetPath', label: '目标路径', type: 'text' },
    ],
  },
  {
    type: 'run-command',
    category: 'action',
    label: '运行命令',
    description: '执行系统命令',
    icon: 'Terminal',
    color: '#4f6ef7',
    inputs: [{ id: 'in', label: '输入', dataType: 'any' }],
    outputs: [{ id: 'out', label: '输出', dataType: 'object' }],
    outputFields: [
      { key: 'stdout', label: '标准输出', type: 'string' },
      { key: 'stderr', label: '错误输出', type: 'string' },
      { key: 'exitCode', label: '退出码', type: 'number' },
    ],
    defaultData: { command: '', workingDir: '', timeout: 30 },
    configSchema: [
      { key: 'command', label: '命令', type: 'textarea', required: true },
      { key: 'workingDir', label: '工作目录', type: 'file-picker' },
      { key: 'timeout', label: '超时(秒)', type: 'number', defaultValue: 30 },
    ],
  },
  {
    type: 'http-request',
    category: 'action',
    label: 'HTTP 请求',
    description: '发送 HTTP 请求',
    icon: 'Globe',
    color: '#4f6ef7',
    inputs: [{ id: 'in', label: '输入', dataType: 'any' }],
    outputs: [{ id: 'out', label: '输出', dataType: 'object' }],
    outputFields: [
      { key: 'status', label: '状态码', type: 'number' },
      { key: 'headers', label: '响应头', type: 'object' },
      { key: 'data', label: '响应数据', type: 'object' },
    ],
    defaultData: { method: 'GET', url: '', headers: '{}', body: '{}', timeout: 30 },
    configSchema: [
      { key: 'method', label: '方法', type: 'select', required: true, options: [
        { label: 'GET', value: 'GET' },
        { label: 'POST', value: 'POST' },
        { label: 'PUT', value: 'PUT' },
        { label: 'DELETE', value: 'DELETE' },
        { label: 'PATCH', value: 'PATCH' },
      ]},
      { key: 'url', label: 'URL', type: 'text', required: true },
      { key: 'headers', label: '请求头', type: 'json' },
      { key: 'body', label: '请求体', type: 'json' },
      { key: 'timeout', label: '超时（秒）', type: 'number' },
    ],
  },
  {
    type: 'clipboard',
    category: 'action',
    label: '剪贴板',
    description: '读写系统剪贴板',
    icon: 'Clipboard',
    color: '#4f6ef7',
    inputs: [{ id: 'in', label: '输入', dataType: 'any' }],
    outputs: [{ id: 'out', label: '输出', dataType: 'object' }],
    outputFields: [
      { key: 'text', label: '剪贴板内容', type: 'string' },
      { key: 'written', label: '已写入内容', type: 'string' },
    ],
    defaultData: { operation: 'read', content: '' },
    configSchema: [
      { key: 'operation', label: '操作', type: 'select', required: true, options: [
        { label: '读取', value: 'read' },
        { label: '写入', value: 'write' },
      ]},
      { key: 'content', label: '内容', type: 'text' },
    ],
  },
  {
    type: 'notify',
    category: 'action',
    label: '系统通知',
    description: '发送系统通知',
    icon: 'Bell',
    color: '#4f6ef7',
    inputs: [{ id: 'in', label: '输入', dataType: 'any' }],
    outputs: [{ id: 'out', label: '输出', dataType: 'object' }],
    outputFields: [
      { key: 'sent', label: '是否发送', type: 'boolean' },
    ],
    defaultData: { title: '', body: '' },
    configSchema: [
      { key: 'title', label: '标题', type: 'text', required: true },
      { key: 'body', label: '内容', type: 'text' },
    ],
  },
  {
    type: 'delay',
    category: 'action',
    label: '延时等待',
    description: '等待指定时间',
    icon: 'Timer',
    color: '#4f6ef7',
    inputs: [{ id: 'in', label: '输入', dataType: 'any' }],
    outputs: [{ id: 'out', label: '输出', dataType: 'any' }],
    outputFields: [],
    defaultData: { duration: 1000 },
    configSchema: [
      { key: 'duration', label: '等待时间(毫秒)', type: 'number', required: true },
    ],
  },

  // ============ 逻辑 ============
  {
    type: 'condition',
    category: 'logic',
    label: '条件判断',
    description: '根据条件走不同分支',
    icon: 'GitBranch',
    color: '#fbbf24',
    inputs: [{ id: 'in', label: '输入', dataType: 'any' }],
    outputs: [
      { id: 'true', label: '是', dataType: 'any' },
      { id: 'false', label: '否', dataType: 'any' },
    ],
    outputFields: [
      { key: 'passed', label: '判断结果', type: 'boolean' },
    ],
    defaultData: { field: '', operator: 'eq', value: '' },
    configSchema: [
      { key: 'field', label: '判断字段', type: 'variable', required: true, placeholder: '选择要判断的变量' },
      { key: 'operator', label: '运算符', type: 'select', required: true, options: [
        { label: '等于', value: 'eq' },
        { label: '不等于', value: 'neq' },
        { label: '大于', value: 'gt' },
        { label: '小于', value: 'lt' },
        { label: '大于等于', value: 'gte' },
        { label: '小于等于', value: 'lte' },
        { label: '包含', value: 'contains' },
        { label: '正则匹配', value: 'matches' },
        { label: '存在', value: 'exists' },
      ]},
      { key: 'value', label: '比较值', type: 'text' },
    ],
  },
  {
    type: 'loop',
    category: 'logic',
    label: '循环',
    description: '遍历数组或重复执行',
    icon: 'Repeat',
    color: '#fbbf24',
    inputs: [{ id: 'in', label: '输入', dataType: 'any' }],
    outputs: [
      { id: 'item', label: '每次', dataType: 'any' },
      { id: 'done', label: '完成', dataType: 'any' },
    ],
    outputFields: [
      { key: 'items', label: '数组', type: 'array' },
      { key: 'mode', label: '模式', type: 'string' },
    ],
    defaultData: { mode: 'array', arrayVar: '', count: 1 },
    configSchema: [
      { key: 'mode', label: '模式', type: 'select', required: true, options: [
        { label: '遍历数组', value: 'array' },
        { label: '重复次数', value: 'count' },
      ]},
      { key: 'arrayVar', label: '数组变量', type: 'variable' },
      { key: 'count', label: '重复次数', type: 'number' },
    ],
  },
  {
    type: 'call-workflow',
    category: 'logic',
    label: '调用工作流',
    description: '调用另一个工作流执行',
    icon: 'Workflow',
    color: '#fbbf24',
    inputs: [{ id: 'in', label: '输入', dataType: 'any' }],
    outputs: [{ id: 'out', label: '输出', dataType: 'object' }],
    outputFields: [
      { key: 'result', label: '执行结果', type: 'object' },
      { key: 'status', label: '执行状态', type: 'string' },
    ],
    defaultData: { workflowId: '' },
    configSchema: [
      { key: 'workflowId', label: '目标工作流', type: 'workflow-picker', required: true },
    ],
  },
  {
    type: 'try-catch',
    category: 'logic',
    label: '错误捕获',
    description: '捕获下游节点错误，走错误分支',
    icon: 'ShieldAlert',
    color: '#fbbf24',
    inputs: [{ id: 'in', label: '输入', dataType: 'any' }],
    outputs: [
      { id: 'success', label: '成功', dataType: 'any' },
      { id: 'error', label: '错误', dataType: 'any' },
    ],
    outputFields: [
      { key: 'error', label: '是否有错误', type: 'boolean' },
      { key: 'message', label: '错误信息', type: 'string' },
    ],
    defaultData: {},
    configSchema: [],
  },
  {
    type: 'variable',
    category: 'logic',
    label: '变量设置',
    description: '设置工作流变量',
    icon: 'Variable',
    color: '#fbbf24',
    inputs: [{ id: 'in', label: '输入', dataType: 'any' }],
    outputs: [{ id: 'out', label: '输出', dataType: 'any' }],
    outputFields: [],
    defaultData: { name: '', value: '' },
    configSchema: [
      { key: 'name', label: '变量名', type: 'text', required: true },
      { key: 'value', label: '变量值', type: 'text', required: true },
    ],
  },
  {
    type: 'retry',
    category: 'logic',
    label: '重试',
    description: '失败后自动重试 N 次',
    icon: 'RotateCcw',
    color: '#fbbf24',
    inputs: [{ id: 'in', label: '输入', dataType: 'any' }],
    outputs: [
      { id: 'task', label: '执行', dataType: 'any' },
      { id: 'success', label: '成功', dataType: 'any' },
      { id: 'error', label: '失败', dataType: 'any' },
    ],
    outputFields: [
      { key: 'attempts', label: '尝试次数', type: 'number' },
      { key: 'success', label: '是否成功', type: 'boolean' },
      { key: 'lastError', label: '最后错误', type: 'string' },
    ],
    defaultData: { maxRetries: 3, delayMs: 1000 },
    configSchema: [
      { key: 'maxRetries', label: '最大重试次数', type: 'number', required: true, defaultValue: 3 },
      { key: 'delayMs', label: '重试间隔(毫秒)', type: 'number', defaultValue: 1000 },
    ],
  },

  // ============ 新增动作 ============
  {
    type: 'transform',
    category: 'action',
    label: '数据转换',
    description: 'JSON 提取、正则匹配、字符串处理',
    icon: 'Shuffle',
    color: '#4f6ef7',
    inputs: [{ id: 'in', label: '输入', dataType: 'any' }],
    outputs: [{ id: 'out', label: '输出', dataType: 'any' }],
    outputFields: [
      { key: 'result', label: '结果', type: 'any' },
      { key: 'type', label: '类型', type: 'string' },
    ],
    defaultData: { operation: 'json-extract', path: '', pattern: '', replacement: '', separator: ',', template: '' },
    configSchema: [
      { key: 'operation', label: '操作', type: 'select', required: true, options: [
        { label: 'JSON 提取', value: 'json-extract' },
        { label: '正则匹配', value: 'regex-match' },
        { label: '字符串替换', value: 'string-replace' },
        { label: '字符串分割', value: 'string-split' },
        { label: '数组合并', value: 'string-join' },
        { label: '解析 JSON', value: 'to-json' },
        { label: '转为字符串', value: 'to-string' },
        { label: '模板渲染', value: 'template' },
      ]},
      { key: 'path', label: 'JSON 路径', type: 'text', placeholder: '如 data.items.0.name' },
      { key: 'pattern', label: '正则/查找', type: 'text', placeholder: '正则表达式或查找文本' },
      { key: 'replacement', label: '替换为', type: 'text' },
      { key: 'separator', label: '分隔符', type: 'text', placeholder: ',' },
      { key: 'template', label: '模板', type: 'textarea', placeholder: '支持 {{变量}} 插值' },
    ],
  },
  {
    type: 'email',
    category: 'action',
    label: '发送邮件',
    description: '通过 SMTP 发送邮件',
    icon: 'Mail',
    color: '#4f6ef7',
    inputs: [{ id: 'in', label: '输入', dataType: 'any' }],
    outputs: [{ id: 'out', label: '输出', dataType: 'object' }],
    outputFields: [
      { key: 'messageId', label: '消息 ID', type: 'string' },
      { key: 'accepted', label: '已接受', type: 'object' },
      { key: 'rejected', label: '已拒绝', type: 'object' },
    ],
    defaultData: { host: '', port: 465, secure: true, user: '', password: '', from: '', to: '', cc: '', subject: '', body: '' },
    configSchema: [
      { key: 'host', label: 'SMTP 服务器', type: 'text', required: true, placeholder: 'smtp.qq.com' },
      { key: 'port', label: '端口', type: 'number', defaultValue: 465 },
      { key: 'secure', label: 'SSL/TLS', type: 'toggle', defaultValue: true },
      { key: 'user', label: '用户名', type: 'text', required: true },
      { key: 'password', label: '密码/授权码', type: 'text', required: true },
      { key: 'from', label: '发件人', type: 'text', placeholder: '留空则使用用户名' },
      { key: 'to', label: '收件人', type: 'text', required: true, placeholder: '多个用逗号分隔' },
      { key: 'cc', label: '抄送', type: 'text' },
      { key: 'subject', label: '主题', type: 'text' },
      { key: 'body', label: '正文', type: 'textarea' },
    ],
  },
  {
    type: 'database',
    category: 'action',
    label: '数据库查询',
    description: '查询 SQLite 或 MySQL 数据库',
    icon: 'Database',
    color: '#4f6ef7',
    inputs: [{ id: 'in', label: '输入', dataType: 'any' }],
    outputs: [{ id: 'out', label: '输出', dataType: 'object' }],
    outputFields: [
      { key: 'rows', label: '查询结果', type: 'object' },
      { key: 'changes', label: '影响行数', type: 'number' },
      { key: 'lastInsertRowid', label: '最后插入 ID', type: 'number' },
    ],
    defaultData: { dbType: 'sqlite', dbPath: '', host: '', port: 3306, user: '', password: '', database: '', query: '', params: '[]' },
    configSchema: [
      { key: 'dbType', label: '数据库类型', type: 'select', required: true, options: [
        { label: 'SQLite', value: 'sqlite' },
        { label: 'MySQL', value: 'mysql' },
      ]},
      { key: 'dbPath', label: '数据库文件', type: 'file-picker' },
      { key: 'host', label: '主机', type: 'text', placeholder: 'localhost' },
      { key: 'port', label: '端口', type: 'number', defaultValue: 3306 },
      { key: 'user', label: '用户名', type: 'text' },
      { key: 'password', label: '密码', type: 'text' },
      { key: 'database', label: '数据库名', type: 'text' },
      { key: 'query', label: 'SQL 查询', type: 'textarea', required: true },
      { key: 'params', label: '查询参数', type: 'json', placeholder: '["value1", "value2"]' },
    ],
  },
  {
    type: 'wifi-login',
    category: 'action',
    label: 'WiFi 登录',
    description: '自动登录 WiFi Portal 认证页面',
    icon: 'Wifi',
    color: '#4f6ef7',
    inputs: [{ id: 'in', label: '输入', dataType: 'any' }],
    outputs: [{ id: 'out', label: '输出', dataType: 'object' }],
    outputFields: [
      { key: 'success', label: '是否成功', type: 'boolean' },
      { key: 'message', label: '消息', type: 'string' },
      { key: 'userName', label: '用户名', type: 'string' },
    ],
    defaultData: { portalUrl: 'http://1.1.1.3/ac_portal', userName: '', password: '' },
    configSchema: [
      { key: 'portalUrl', label: 'Portal 地址', type: 'text', required: true, placeholder: 'http://1.1.1.3/ac_portal' },
      { key: 'userName', label: '用户名', type: 'text', required: true },
      { key: 'password', label: '密码', type: 'text', required: true },
    ],
  },
];

export function getNodeDefinition(type: string): NodeDefinition | undefined {
  return nodeDefinitions.find((d) => d.type === type);
}

export function getNodesByCategory(category: string): NodeDefinition[] {
  return nodeDefinitions.filter((d) => d.category === category);
}
